[workspace]
members = ["game", "bundle", "util"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Rachel Knight <rachel@automorphi.city>"]

[profile.dev.build-override]
opt-level = 3

